curl --location --request POST 'https://app.eshipz.com/api/v1/create-shipments/rule-based' \
--header 'Content-Type: application/json' \
--header 'X-API-TOKEN: 630864660afce06455b59982' \
--data-raw '{"billing":{"paid_by":"recipient"},
"vendor_id":null,"slug":null,"service_type":null,
"description":"Warehouse Now","purpose":"commercial",
"order_source":"OFFLINE","parcel_contents":"commercial",
"is_document":false,"customer_reference":"6346865e9afd9a10b8619017",
"invoice_number":"KASBANKAR11980","is_cod":false,
"collect_on_delivery":{"amount":0,"currency":"INR"},
"shipment":{"ship_from":{"contact_name":"Kashika Agritech Private Limited",
"company_name":"Kashika Agritech Private Limited","street1":"Houtower wali nothing lajpat nagar",
"street2":"Houtower wali nothing lajpat nagar","city":"Lucknow","state":"Karnataka",
"postal_code":"122006","phone":"9599267414","email":"b.srinibas@agrictools.com",
"tax_id":"","country":"IN","type":"business"},
"ship_to":{"contact_name":"VETRI VINAYAGAR FARM NEEDS",
              "company_name":"",
              "street1":"No:43,EX-15B,Near by Pass Road, NH45 Ayyappan kovil, ALTAJ hotel, Chengalpattu 603002 Tamil Nadu",
              "street2":"","city":"Chengalpattu",
 "state":"Tamil Nadu","postal_code":"603002","phone":"8056252495","country":"IN",
 "type":"residential"},"return_to":{"contact_name":"Kashika Agritech Private Limited",
 "company_name":"Kashika Agritech Private Limited","street1":"Houtower wali nothing lajpat nagar",
 "street2":"Houtower wali nothing lajpat nagar","city":"Lucknow","state":"Karnataka",
 "postal_code":"122006","phone":"9599267414","email":"b.srinibas@agrictools.com",
 "tax_id":"","country":"IN","type":"business"},"is_reverse":false,
 "is_to_pay":false,"parcels":[{"description":"BOX",
 "box_type":"custom","weight":{"value":1.21,"unit":"kg"},
 "dimension":{"width":10,"height":10,"length":10,"unit":"cm"},
 "items":[{"description":"Agriculture","origin_country":"IN",
 "quantity":1,"hs_code":"","sku":"OILTANKANDTANKSTRAINER170F-192F",
 "price":{"amount":18,"currency":"INR"},
 "weight":{"value":1.21,"unit":"kg"}}]}]}}'